const PROMISE_SPLITTER_MAX_REQUEST_LOCALSTORAGE_NAME = 'YCLIENTS__BOOSTER__PROMISE_SPLITTER_MAX_REQUESTS';
const PROMISE_SPLITTER_MAX_RETRY_LOCALSTORAGE_NAME   = 'YCLIENTS__BOOSTER__PROMISE_SPLITTER_MAX_REQUESTS';

export const PROMISE_SPLITTER_MAX_REQUESTS = parseInt(localStorage.getItem(PROMISE_SPLITTER_MAX_REQUEST_LOCALSTORAGE_NAME) ?? '5');
export const PROMISE_SPLITTER_MAX_RETRY    = parseInt(localStorage.getItem(PROMISE_SPLITTER_MAX_RETRY_LOCALSTORAGE_NAME) ?? '2');